//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementEntity1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Room
    {
        public Room()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int roomId { get; set; }
        [Required(ErrorMessage = "Please Select Room Type")]  
        public string roomType { get; set; }
        [Required(ErrorMessage = "Please Select Number Of Rooms")]
        [RegularExpression("([1-9][0-9]*([0-9]+)?|0+[0-9]*[1-9][0-9]*$.)", ErrorMessage = "Invalid entry")]
        public Nullable<int> roomNumber { get; set; }
        public Nullable<int> roomPrice { get; set; }
    
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
